### PR TITLE
feat: implement logging of builds in unique txt files and update logg…

### LINKED ISSUE #27: Implement unique URL for each build (Related to task `P7`)
~~Description: If each build in `/build_history` is logged in its own file, it is straightforward to implement the listing of previous builds in the browser.~~

## Description:
According to task `P7` in the assignment specification, the CI server needs to the following:

1. Keep the history of the past builds*"
2. This history persists even if the server is rebooted*"
3. Each build is given a unique URL, that is accessible to get the build information (commit identifier, build date, build logs)
4. One URL exists to list all builds.

## Definition of done
The first and second parts are already handled by the `ci_server`. This issue will be about implementing the third part. The fourth part is solved by issue #39.

A file is created for each build where each file is named with the full time stamp, for example:

`build_2024-02-09_14-15-23-866.txt` (YYYY-MM-DD_HH-MM-SS-sss)

Each build gets a unique txt file in `build_history/`, tests are implemented and the change is pushed and then merged to main.

## Testing
Test that the correct file is created when a new build is logged.

### PR DESCRIPTION
**Pull request by sebastianmonten**
…er tests in test_logger.py

Description: Implement logging of builds in unique txt files in `build_history` instead of a log file for each day. The reason for this is that displaying the build logs in html is easier if they ar already organised in separate txt files.

closes #27

### CODE REVIEW

**Comment by rasmus-d** [comment]
Looks good! Why not go further and make the logged build be formatted directly as html?

so log_build() would write something like
```
<html>
<h1> Build for commit {commit_id} </h1>
<table ...
... data ...
.... data... 
</html>
```
Easily done with Flask templates (lookup jinja).

Just an idea, what do you think?

**Comment by sebastianmonten** [comment]
Cool, I'll try it out on this branch!

**Comment by sebastianmonten** [comment]
I will also include commit hash in file name of each build

**Comment by sebastianmonten** [comment]
I made som changes in Logger class in `logger.py` that I am not sure about. In order for the build log txt files to have the individual commit id:s in their name, the `log_build()` now creates a new build_logger when it's called. 

I am also not sure if the updated tests in `test_logger.py` works, since I can't run the system with this version of the project that this branch is based on.

**Review by Stenmarken — APPROVED** [review]

**Pull request merged**
