### PR TITLE
feat: add test structure for CI

### LINKED ISSUE #7: Add CI test structure
Description: The CI should perform a static syntax check and tests for the various parts of the CI. Therefore, we need a structure in which these tests can be run. Consider using a makefile or something to make the tests easy to run.

Description of done: Implement a file structure where one can add unit tests for the various parts of the CI and a static syntax check.

### PR DESCRIPTION
**Pull request by Stenmarken**
Add one file for compilation tests, one for unit tests, and one script for running all tests.

Resolves #7

### CODE REVIEW

**Comment by rasmus-d** [comment]
I made a mistake with the naming of ci-server and test_ci-server: python modules do not work with kebab case. Please rename the directories to to ci_server and test_ci_server.

**Comment by rasmus-d** [comment]
I think we want to have the subprocess that runs the tests in ci_server/ actually, since we're not testing the program itself, but another copy of it in tmp/.

**Comment by Stenmarken** [comment]
By the subprocess that runs the tests, do you mean test.py?

**Comment by rasmus-d** [comment]
> By the subprocess that runs the tests, do you mean test.py?

I mean we want to have something like ci_server/ci_logic.py, which contains a subprocess call to the test.py* of the project contained in tmp/ -- the project being CI:d. We do not want the CI actions to be included in our own test-suite, running the tests of a branch being CId is the job of the core application.

We probably want, in ci_server/ci_logic.py (open for other names), to do a `os.chdir('tmp/')`, then a subprocess call to run a `git clone`, then a subprocess call to call the tests of the cloned repo, and probably more subprocesses like deleting the repo when done and reporting any error, extracting logs, etc, etc, etc.
 
\* Or don't use a test.py file for testing and just run `python3 -m unittest discover` or `make`-- but thats your call.

What do you think, do you get what i mean? It gets a bit confusing with the whole dogfooding...

**Comment by Stenmarken** [comment]
I think so. I've now moved tests.py to be in ci_server and tests.py will now look for the test_ci_server in the /tmp/ directory. I still use a test.py file so I can get a boolean value for whether the tests pass or not. The subprocesses for cloning, running tests, and deleting will be added with issue #11.

**Comment by rasmus-d** [comment]
Snyggt!

**Pull request merged**
