### PR TITLE
fix: bugfix nonexisting directories

### LINKED ISSUE #26: FileNotFoundError when running ci_logic.py
Description: `ci_logic` doesn't seem to find the directory /tmp/log. My guess it that we first have to make sure it exists before attempting to write to a file there. According the error messages from running `python3 ci_server/ci_logic.py` from root folder, the error occurs in `test_logger.py`. 

Definition of done: Locate and fix the bug.

### LINKED ISSUE #32: Potential bug when running `ci_server`
## Reproduction:
Run `pdm run ci-server` without a `log` directory and an error message like this will occur:

```
  File "[...]/assignment-2/ci_server/logger.py", line 37, in __init__
    handler = logging.FileHandler(f"log/{filename}")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[...]
FileNotFoundError: [Errno 2] No such file or directory: '[...]/assignment-2/log/2024-02-10.log'
```

## Thoughts on fix
This seems to occur because we don't check if such a directory (*i.e.,* `log`) exists.

### PR DESCRIPTION
**Pull request by dantevi**
Resolves #26 #32

### CODE REVIEW

**Comment by dantevi** [comment]
I haven't tested if there are any potential issues when the code needs to create the `tmp/` folder, because I am not entirely sure how to test that. Can somebody double check this?

**Comment by dantevi** [comment]
Also, can somebody confirm that it is only the `log/`, `build_history/` and `tmp/` directories that are  created by the program and that we don't have to handle any other directories?

**Comment by dantevi** [comment]
I also gitignored the mentioned directories (*i.e.,* `log/` *and* `build_history/` *as well as* `tmp/` *which was already gitignored*), however I'm not sure if they were left out from the `.gitignore` intentionally. Can someone confirm that they should or should not be gitignored?

**Comment by rasmus-d** [comment]
> I haven't tested if there are any potential issues when the code needs to create the `tmp/` folder, because I am not entirely sure how to test that. Can somebody double check this?

The current tmp/ creation deletion is a bit iffy in that tmp/ does not get deleted if the program fails -- but that might be a feature, not a bug... This causes a direct failure when running the ci_logic again since the folder is not empty. Otherwise the git subprocess takes care of creating the folder.

> Also, can somebody confirm that it is only the `log/`, `build_history/` and `tmp/` directories that are created by the program and that we don't have to handle any other directories?

Yes, they should be the only directories (except for ci_server and test_ci_server) that are required to run the server.

> I also gitignored the mentioned directories (_i.e.,_ `log/` _and_ `build_history/` _as well as_ `tmp/` _which was already gitignored_), however I'm not sure if they were left out from the `.gitignore` intentionally. Can someone confirm that they should or should not be gitignored?

They should be ignored.


This change looks good. Bra jobbat!

**Review by rasmus-d — APPROVED** [review]
Looks good!

**Pull request merged**
